### ISSUE TITLE
The release contains a trojan RDN/Generic.dx. Do NOT download

### ISSUE THREAD

**Issue by tsenay** [demondevin/GitHubDesktopPortable#1]

**Comment by demondevin** [comment]
No it doesn't. False positive you fucking moron

**Comment by tsenay** [comment]
McAfee says so. So it can be interesting for you to submit your file to McAfee to to fix that.
Greetings to you and your family.

**Comment by demondevin** [comment]
McAfee is a cheap knockoff. Stop using the free version and get a real Antivirus.

**Comment by tsenay** [comment]
It's the enterprise version with virus definition update every 15 minutes. So I won't be the last person with that issue.

**Comment by demondevin** [comment]
McAfee is crapware period.

https://www.virustotal.com/file/2320b5b2c88ec6234df56273367adf982c330fa5a8a4deca4606853c0866f872/analysis/1505555330/

Notice how all the real AntiVirus's say it's clean?

And just so you are aware, GitHub is an **OPEN SOURCE** forum which means that anything and everything has it's source code available to the public for viewing. Now I dare you to look through the source code of my GitHub Portable and tell me where you see any malicious code.

It's people like you who don't know anything about anything who give us small time developers a bad name. Do some research before you make a outlandish accusation like that again.

**Comment by tsenay** [comment]
I had a doubt because you uploaded an exe file on your repo.

**Comment by DoomStorm** [comment]
I have been using the Portable (who is a reliable source as well) and so far I have not been infected by anything, even running it out of any virtual environment.
I have sent the same portable to various other Anti-Virus companies for a scan, which leads to nothing.

Regards

**Comment by demondevin** [comment]
Thanks @DoomStorm

**Comment by demondevin** [comment]
@tsenay I'd like to apologies for my rough response above. To my defense, however, I want you to know that I have no patience for things like this. Saying someone's work has a virus can really hinder a man's credibility for anything else he might develop.

**Comment by tsenay** [comment]
I also should be more factual. I’m not a frequent user of Windows, I mostly work on Linux. So I Learned today that antivirus are not accurate. Linux rules!!
